name: Deploy to GitHub Pages
on:
  push:
    branches:
      - CI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup "wasm32-unknown-unknown" target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup "wasm-bindgen-cli"
        run: cargo install wasm-bindgen-cli

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        run: |
          yarn
          yarn run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
